export const ERRORS = {
  BAD_REQUEST: 'BAD_REQUEST',
  SERVER_ERROR: 'SERVER_ERROR',
  EMAIL_REGISTER: 'EMAIL_REGISTER',
  NOT_FOUND: 'EMAIL_REGISTER'
}

export const VIDEO_ERRORS = {
  INVALID_TOKEN: 'INVALID_TOKEN',
  MISSING_TOKEN: 'MISSING_TOKEN'
}
